// <auto-generated />
using AVSBiro.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AVSBiro.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0-preview.5.22302.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AVSBiro.Shared.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<decimal>("Brutto2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Contract")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmploymentEnded")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IBAN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Obsolete")
                        .HasColumnType("bit");

                    b.Property<bool>("PaidOvertime")
                        .HasColumnType("bit");

                    b.Property<int>("PositionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PositionId");

                    b.ToTable("Emmployees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brutto2 = 10000m,
                            Contract = "Contract",
                            EmploymentEnded = false,
                            FirstName = "Nikola",
                            IBAN = "ibanNikola",
                            LastName = "Lovrić",
                            Obsolete = false,
                            PaidOvertime = false,
                            PositionId = 1
                        },
                        new
                        {
                            Id = 2,
                            Brutto2 = 10000m,
                            Contract = "Contract2",
                            EmploymentEnded = false,
                            FirstName = "Danijel",
                            IBAN = "ibanDanijel",
                            LastName = "Pavić",
                            Obsolete = false,
                            PaidOvertime = false,
                            PositionId = 2
                        });
                });

            modelBuilder.Entity("AVSBiro.Shared.Position", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Obsolete")
                        .HasColumnType("bit");

                    b.Property<int>("PayRank")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Postions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "PLC Programmer",
                            Obsolete = false,
                            PayRank = 50000
                        },
                        new
                        {
                            Id = 2,
                            Name = "Junior Developer",
                            Obsolete = false,
                            PayRank = 10000
                        });
                });

            modelBuilder.Entity("AVSBiro.Shared.Employee", b =>
                {
                    b.HasOne("AVSBiro.Shared.Position", "Position")
                        .WithMany()
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Position");
                });
#pragma warning restore 612, 618
        }
    }
}
